### ISSUE TITLE
Allow settings via environment variables

### ISSUE THREAD

**Issue by mhubig** [partkeepr/PartKeepr#838]
I'm trying to build a [Dockerfile](https://github.com/mhubig/docker-partkeepr/tree/develop) to ease and speed up the deployment of Partkeepr. One particular problem I found is the use of the `parameters.php` file. In order to be able to build a stateless and reusable Docker image, I need to be able to set the values of the parameters file via some environment variables.

My goal is to be able to deploy partkeepr with a `docker-compose.yml` file like this:

```
version: "3"
services:
 
  partkeepr:
    image: mhubig/partkeepr
    environment:
      - PARTKEEPR_DATABASE_HOST=database
      - PARTKEEPR_DATABASE_NAME=partkeepr
      - PARTKEEPR_DATABASE_USER=partkeepr
      - PARTKEEPR_DATABASE_PASS=partkeepr
    ports:
      - "80:80"
    volumes:
      - partkeepr-data:/var/www/html/data
    depends_on:
      - database

  database:
    image: mariadb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=partkeepr
      - MYSQL_USER=partkeepr
      - MYSQL_PASSWORD=partkeepr
    volumes:
      - mysql-data:/var/lib/mysql
 
volumes:
  partkeepr-data:
  mysql-data:
```

I tried using `getenv` but it didn't work out:

```
$container->setParameter('database_host', getenv('PARTKEEPR_DATABASE_HOST'));
$container->setParameter('database_name', getenv('PARTKEEPR_DATABASE_NAME'));
$container->setParameter('database_port', getenv('PARTKEEPR_DATABASE_PORT'));
$container->setParameter('database_user', getenv('PARTKEEPR_DATABASE_USER'));
$container->setParameter('database_password', getenv('PARTKEEPR_DATABASE_PASS'));
```

So my only choice for now would be an entrypoint script which takes the environment parameters and generates a working `parameters.php` file ... but this is not a very clean approach!
